package com.invoiceme.domain.payment;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("Payment Domain Entity Tests")
class PaymentTest {
    
    @Test
    @DisplayName("Should create payment with valid data")
    void createPayment_WithValidData_ShouldCreate() {
        // Given
        UUID invoiceId = UUID.randomUUID();
        BigDecimal amount = new BigDecimal("100.00");
        LocalDateTime paymentDate = LocalDateTime.now();
        
        // When
        Payment payment = new Payment(invoiceId, amount, paymentDate);
        
        // Then
        assertEquals(invoiceId, payment.getInvoiceId());
        assertEquals(amount, payment.getAmount());
        assertEquals(paymentDate, payment.getPaymentDate());
        // Note: ID is generated by JPA on persist, so we don't check it in unit tests
        assertNotNull(payment.getCreatedAt());
    }
    
    @Test
    @DisplayName("Should throw exception when creating payment with null invoice ID")
    void createPayment_WithNullInvoiceId_ShouldThrowException() {
        // Given
        BigDecimal amount = new BigDecimal("100.00");
        LocalDateTime paymentDate = LocalDateTime.now();
        
        // When/Then
        assertThrows(IllegalArgumentException.class, 
                () -> new Payment(null, amount, paymentDate));
    }
    
    @Test
    @DisplayName("Should throw exception when creating payment with null amount")
    void createPayment_WithNullAmount_ShouldThrowException() {
        // Given
        UUID invoiceId = UUID.randomUUID();
        LocalDateTime paymentDate = LocalDateTime.now();
        
        // When/Then
        assertThrows(IllegalArgumentException.class, 
                () -> new Payment(invoiceId, null, paymentDate));
    }
    
    @Test
    @DisplayName("Should throw exception when creating payment with zero amount")
    void createPayment_WithZeroAmount_ShouldThrowException() {
        // Given
        UUID invoiceId = UUID.randomUUID();
        BigDecimal amount = BigDecimal.ZERO;
        LocalDateTime paymentDate = LocalDateTime.now();
        
        // When/Then
        assertThrows(IllegalArgumentException.class, 
                () -> new Payment(invoiceId, amount, paymentDate));
    }
    
    @Test
    @DisplayName("Should throw exception when creating payment with negative amount")
    void createPayment_WithNegativeAmount_ShouldThrowException() {
        // Given
        UUID invoiceId = UUID.randomUUID();
        BigDecimal amount = new BigDecimal("-10.00");
        LocalDateTime paymentDate = LocalDateTime.now();
        
        // When/Then
        assertThrows(IllegalArgumentException.class, 
                () -> new Payment(invoiceId, amount, paymentDate));
    }
    
    @Test
    @DisplayName("Should throw exception when creating payment with null payment date")
    void createPayment_WithNullPaymentDate_ShouldThrowException() {
        // Given
        UUID invoiceId = UUID.randomUUID();
        BigDecimal amount = new BigDecimal("100.00");
        
        // When/Then
        assertThrows(IllegalArgumentException.class, 
                () -> new Payment(invoiceId, amount, null));
    }
}

